Repository prgrms-web-devcourse/OFF_Design_System, pull requests merged in 2023-10, with the labels that each got.

#9 Feat 기본 배포 라이브러리 설정
  .eslintrc.cjs
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  index.html
  index.ts
  package-lock.json
  package.json
  postcss.config.js
  public/vite.svg
  src/App.tsx
  src/assets/react.svg
  src/components/buttons/JGButton.tsx
  src/index.css
  src/main.tsx
  src/vite-env.d.ts
  tailwind.config.js
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: 문서, 기능

#14 라이브러리 관련 세팅 작업
  LICENSE
  README.md
  package-lock.json
  package.json
  scripts/release.sh
Labels: 문서, 기능

#19 스토리북 배포 자동화 작업
  .github/workflows/chromatic.yml
  package-lock.json
  package.json
  src/components/buttons/JGButton.stories.tsx
Labels: 문서, 기능

#17 :tada: 이미지 업로더 컴포넌트 구현
  index.ts
  package-lock.json
  package.json
  src/App.tsx
  src/components/uploads/ImageUploader.tsx
Labels: 리뷰 요청, 기능

#15 feat: 범진 버튼 컴포넌트 구현
  src/components/buttons/BJbutton.tsx
Labels: 프론트, 기능

#29 feat: 이미지 업로더 컴포넌트 스토리북 추가
  .github/workflows/chromatic.yml
  index.ts
  package-lock.json
  src/App.tsx
  src/components/uploads/ImageUploader/ImageUploader.stories.tsx
  src/components/uploads/ImageUploader/ImageUploader.tsx
Labels: 리뷰 요청, 기능

#27 feat:bj button npm 배포
  package.json
Labels: 기능

#35 24 textarea 컴포넌트 관련 작업
  index.ts
  package-lock.json
  package.json
  src/App.tsx
  src/components/buttons/JGButton.stories.tsx
  src/components/textarea/Textarea.stories.tsx
  src/components/textarea/Textarea.tsx
Labels: 기능

#31 28 아바타 컴포넌트 추가
  index.ts
  package.json
  src/App.tsx
  src/components/common/Avatar/Avatar.stories.tsx
  src/components/common/Avatar/Avatar.tsx
Labels: 기능, 수정 중

#32 feat:bj button 스토리북 배포
  src/components/buttons/BJButton.stories.tsx
Labels: 기능

#41 40 silder 컴포넌트 구현
  src/components/silder/Slider.stories.tsx
  src/components/silder/Slider.tsx
Labels: 기능

#45 index.ts파일에 input컴포넌트 추가
  index.ts
Labels: 기능

#48 42 아바타 컴포넌트 리팩토링
  package-lock.json
  src/App.tsx
  src/components/common/Avatar/Avatar.stories.tsx
  src/components/common/Avatar/Avatar.tsx
  src/components/uploads/ImageUploader/ImageUploader.stories.tsx
Labels: 리뷰 요청, 기능
